# theme: jekyll-theme-hacker
title: Let's learn DevOps together
description: "Practical tasks to learn more about DevOps"
author:
  name: "Alex"
  email: "korneevayu@gmail.com"
  url: "https://notes.makvaz.com/"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Alex"
year : "2021"
