---
name: Upload Release Asset

on:
  push:
    branches:
      - github_workflow

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/korney4eg/change-checker:v0.3.1
      options: "-v /home/runner/work/korney4eg.github.io/:/opt/"
    steps:
         - name: Log the node version
           run: |
             ls -l /opt/ /github/home/ /github/home/
             # /change-checker check -c /opt/.github/actions/config.yaml -u master -b $GITHUB_SHA -d
