---
name: Notify about new articles on Pull Requests

on:
  push
  # pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/korney4eg/change-checker:v0.3.1
    steps:
         - name: Log the node version
           env:
            DISCORD_API: ${{ secrets.DISCORD_API }}
            DISCORD_CHANNEL_URL: ${{ secrets.DISCORD_CHANNEL_URL }}
           run: |
             git clone https://github.com/korney4eg/korney4eg.github.io/ > /dev/null
             cd korney4eg.github.io/
             echo $(git merge-base $GITHUB_SHA origin/$GITHUB_BASE_REF)
             echo $GITHUB_BASE_REF
             # git checkout $(git merge-base $GITHUB_SHA origin/$GITHUB_BASE_REF) > /dev/null
             bundle install > /dev/null
             # /change-checker check -c config.yaml -u master -b $(git merge-base $GITHUB_SHA origin/$GITHUB_BASE_REF) -d
