---
name: Notify about new articles on Pull Requests

on: 
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/korney4eg/change-checker:v0.3.1
    steps:
         - name: Notify on new content on Discord
           env:
            DISCORD_API: ${{ secrets.DISCORD_API }}
            DISCORD_CHANNEL_URL: ${{ secrets.DISCORD_CHANNEL_URL }}
           run: |
             env
             git clone https://github.com/korney4eg/korney4eg.github.io/
             cd korney4eg.github.io/
             echo $GITHUB_HEAD_REF
             git checkout $GITHUB_HEAD_REF
             bundle install
             echo "I finished"
             /change-checker check -c config.yaml -u $GITHUB_HEAD_REF -b master -d
